config/routes.rb
Rails.application.routes.draw do
  resources :numsets
  resources :reps
  devise_for :users
  resources :categories
  resources :exercises
  resources :workouts

  resources :users, only: [:show]

  root "workouts#index"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :workouts

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base


  has_many :workouts_exercises
  has_many :workouts, through: :workouts_exercises
  has_many :reps
  has_many :numsets

  accepts_nested_attributes_for :reps, allow_destroy: true
  accepts_nested_attributes_for :numsets, allow_destroy: true


end

app/models/numset.rb
class Numset < ActiveRecord::Base

  belongs_to :exercise

end

app/models/rep.rb
class Rep < ActiveRecord::Base

  belongs_to :exercise

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts

end

app/models/workout.rb
class Workout < ActiveRecord::Base

  belongs_to :category
  has_many :workouts_exercises
  has_many :exercises, through: :workouts_exercises
  belongs_to :user

  accepts_nested_attributes_for :exercises, allow_destroy: true

end ## class end

app/models/workouts_exercise.rb
class WorkoutsExercise < ActiveRecord::Base

  belongs_to :workout
  belongs_to :exercise

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)

    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end



end ## class end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
    @exercises = Exercise.all
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.save
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    @exercise.update(exercise_params)
  end

  def delete
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name)
  end



end ## class end

app/controllers/numsets_controller.rb
# I don't think we're using this controller, delete it
class NumsetsController < ApplicationController
  #
  # def new
  #   @numset = Numset.new
  # end

  def create
    @numset = Numset.new(numset_params)
    @numset.save
  end

  def edit
    @numset = Numset.find(params[:id])
  end

  def update
    @numset = Numset.find(params[:id])
    @numset.update(numset_params)
  end

  def destroy
    @numset = Numset.find(params[:id])
    @numset.destroy
  end

  private

  def numset_params
    params.require(:numset).permit(:number)
  end


end ## class end

app/controllers/reps_controller.rb
# This controller isn't being used, I'd delete it.
class RepsController < ApplicationController

  def create
    @rep = Rep.new(rep_params)
    @rep.save
  end

  def edit
    @rep = Rep.find(params[:id])
  end

  def update
    @rep = Rep.find(params[:id])
    @rep.update(rep_params)
  end

  def destroy
    @rep = Rep.find(params[:id])
    @rep.destroy
  end

  private

  def rep_params
    params.require(:rep).permit(:number)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # def index
  #   @users = User.all
  # end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new # GET /workouts/new - just presents the form to the user
    @workout = Workout.new  ## this instantiates a new workout object
  end

  def create  # POST /workouts - processes the form
    @workout = current_user.workouts.build(workout_params)
    @workout.save

    redirect_to workouts_path
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    @workout.update(workout_params)

    redirect_to workouts_path
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    redirect_to workouts_path
  end

  private

  def workout_params
    params.require(:workout).permit(:title, :category_id, exercises_attributes: [:id, :name, :_destroy, reps_attributes: [:id, :number, :_destroy], numsets_attributes: [:id, :number, :_destroy]])
  end


end ## class end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    # binding.pry
    new_object = f.object.send(association).klass.new
                #  f.object #=> #<Workout>
                #
                #  workout.send(:exercises) #=> Exercise::ActiveRecord_Associations_CollectionProxy
                #  f.object.send(association).klass #=> Exercise
                #  #<Exercise>

    id = new_object.object_id

    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end



end ## class end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/numsets_helper.rb
module NumsetsHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/helpers/workouts_exercises_helper.rb
module WorkoutsExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutRails</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->

</head>
<body>

    <%= render "navbar/nav" %>
    <%= yield %>



</body>
</html>

app/views/navbar/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Workout App", workouts_path, { :class => "navbar-brand"} %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <% if user_signed_in? %>
        <li><%= link_to "Home", user_path(current_user) %></li>
        <li><%= link_to "Workouts", workouts_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
        <li><%= link_to "New Workout", new_workout_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path %></li>
        <!-- <li>Welcome, <%= current_user.email %></li> -->
        <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
        <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Separated link</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">One more separated link</a></li>
      </ul>
    </li> -->
  </ul>
  <!-- <form class="navbar-form navbar-left" role="search">
  <div class="form-group">
  <input type="text" class="form-control" placeholder="Search">
</div>
<button type="submit" class="btn btn-default">Submit</button>
</form> -->
<!-- <ul class="nav navbar-nav navbar-right">
<li><a href="#">Link</a></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="#">Action</a></li>
<li><a href="#">Another action</a></li>
<li><a href="#">Something else here</a></li>
<li role="separator" class="divider"></li>
<li><a href="#">Separated link</a></li>
</ul>
</li>
</ul> -->
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>