config/routes.rb
Rails.application.routes.draw do
  resources :numsets
  resources :reps
  devise_for :users
  resources :categories
  resources :exercises
  resources :workouts

  resources :users, only: [:show]

  root "workouts#index"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :workouts

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base


  has_many :workouts_exercises
  has_many :workouts, through: :workouts_exercises
  has_many :reps
  has_many :numsets

  accepts_nested_attributes_for :reps, allow_destroy: true
  accepts_nested_attributes_for :numsets, allow_destroy: true


end

app/models/numset.rb
class Numset < ActiveRecord::Base

  belongs_to :exercise

end

app/models/rep.rb
class Rep < ActiveRecord::Base

  belongs_to :exercise

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts

end

app/models/workout.rb
class Workout < ActiveRecord::Base

  belongs_to :category
  has_many :workouts_exercises
  has_many :exercises, through: :workouts_exercises
  belongs_to :user

  accepts_nested_attributes_for :exercises, allow_destroy: true

end ## class end

app/models/workouts_exercise.rb
class WorkoutsExercise < ActiveRecord::Base

  belongs_to :workout
  belongs_to :exercise

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password,:username) }

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation,:username) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation,:username) }

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)

    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end



end ## class end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
    @exercises = Exercise.all
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.save
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    @exercise.update(exercise_params)
  end

  def delete
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name)
  end



end ## class end

app/controllers/numsets_controller.rb
# I don't think we're using this controller, delete it
class NumsetsController < ApplicationController
  #
  # def new
  #   @numset = Numset.new
  # end

  def create
    @numset = Numset.new(numset_params)
    @numset.save
  end

  def edit
    @numset = Numset.find(params[:id])
  end

  def update
    @numset = Numset.find(params[:id])
    @numset.update(numset_params)
  end

  def destroy
    @numset = Numset.find(params[:id])
    @numset.destroy
  end

  private

  def numset_params
    params.require(:numset).permit(:number)
  end


end ## class end

app/controllers/reps_controller.rb
# This controller isn't being used, I'd delete it.
class RepsController < ApplicationController

  def create
    @rep = Rep.new(rep_params)
    @rep.save
  end

  def edit
    @rep = Rep.find(params[:id])
  end

  def update
    @rep = Rep.find(params[:id])
    @rep.update(rep_params)
  end

  def destroy
    @rep = Rep.find(params[:id])
    @rep.destroy
  end

  private

  def rep_params
    params.require(:rep).permit(:number)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # def index
  #   @users = User.all
  # end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new # GET /workouts/new - just presents the form to the user
    @workout = Workout.new  ## this instantiates a new workout object
  end

  def create  # POST /workouts - processes the form
    @workout = current_user.workouts.build(workout_params)
    @workout.save

    redirect_to workouts_path
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    @workout.update(workout_params)

    redirect_to workouts_path
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    redirect_to workouts_path
  end

  private

  def workout_params
    params.require(:workout).permit(:title, :category_id, exercises_attributes: [:id, :name, :_destroy, reps_attributes: [:id, :number, :_destroy], numsets_attributes: [:id, :number, :_destroy]])
  end


end ## class end

app/controllers/workouts_exercises_controller.rb
# I'd delete this controller too.
class WorkoutsExercisesController < ApplicationController

  # def new
  #   @workout = Workout.new
  #   @workout.exercises.build
  #   @workout.workouts_exercises.build
  # end


end ## class end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    # binding.pry
    new_object = f.object.send(association).klass.new
                #  f.object #=> #<Workout>
                #
                #  workout.send(:exercises) #=> Exercise::ActiveRecord_Associations_CollectionProxy
                #  f.object.send(association).klass #=> Exercise
                #  #<Exercise>

    id = new_object.object_id

    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end



end ## class end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/numsets_helper.rb
module NumsetsHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/helpers/workouts_exercises_helper.rb
module WorkoutsExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/categories/_categoryForm.html.erb
<%= form_for @category do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'categoryForm' %>

app/views/categories/index.html.erb
<div class="bs-example col-md-7 col-md-offset-2 col-lg-7 col-lg-offset-2 col-sm-12 col-xs-12" data-example-id="hoverable-table">
  <table class="table table-hover">
    <thead>
      <tr>
        <!-- <th>#</th> -->
        <th class="text-center"><h3>Category</h3></th>
        <th class="text-center"><h3>Edit</h3></th>
        <th class="text-center"><h3>Delete</h3></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <!-- <th scope="row">1</th> -->
        <td class="text-center"><%= link_to "#{category.title}", category_path(category) %></td>
        <td class="text-center"><%= link_to "Edit", edit_category_path(category) %></td>
        <td class="text-center"><%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, category_path(category), method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="newcat">
    <button class="btn btn-primary"><%= link_to "New Category", new_category_path %></button>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'categoryForm' %>

app/views/categories/show.html.erb
<div class="bs-example col-md-7 col-md-offset-2 col-lg-7 col-lg-offset-2 col-sm-12 col-xs-12" data-example-id="hoverable-table">
  <h1 class="text-center"><%= @category.title %></h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <!-- <th>#</th> -->
        <th class="text-center"><h3>Workout</h3></th>
        <th class="text-center"><h3>Created By</h3></th>
        <!-- <th class="text-center"><h3>Delete</h3></th> -->
      </tr>
    </thead>
    <tbody>
      <% @category.workouts.each do |workout| %>
      <tr>
        <!-- <th scope="row">1</th> -->
        <td class="text-center"><%= link_to "#{workout.title}", workout_path(workout) %></td>
        <td class="text-center"><%= link_to "#{workout.user.username}", user_path(workout.user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<h1>Users index page</h1>

<% @users.each do |user| %>
  <%= user.email %>
  <%= link_to "User", user_path(user) %>
<% end %>

app/views/users/show.html.erb
<div class="bs-example col-md-7 col-md-offset-2 col-lg-7 col-lg-offset-2 col-sm-12 col-xs-12" data-example-id="hoverable-table">
  <h1><%= @user.username %>'s Workouts</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <!-- <th>#</th> -->
        <th class="text-center"><h3>Workout</h3></th>
        <th class="text-center"><h3>Category</h3></th>
      </tr>
    </thead>
    <tbody>
      <% @user.workouts.each do |workout| %>
      <tr>
        <!-- <th scope="row">1</th> -->
        <td class="text-center"><%= link_to "#{workout.title}", workout_path(workout) %></td>
        <td class="text-center"><%= link_to "#{workout.category.title}", category_path(workout.category) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/workouts/_exercise_fields.html.erb
<div id="exercise_fields">
  <h3>Exercise:</h3><br>
  <div class="row">
      <%= f.label :name, class: "col-lg-2 col-md-2 col-sm-2 col-xs-4" %>
      <%= f.text_field :name, class: "col-lg-4 col-md-5 col-sm-5 col-xs-5" %>
      <%= f.hidden_field :_destroy %>
      <%= link_to "", "#", class: "remove_exercise_fields col-lg-2 col-md-3 col-sm-5 col-xs-2 glyphicon glyphicon-remove" %>
  </div>
  <br>
  <%= f.fields_for :numsets do |set| %>
    <%= render "numset_fields", f: set %>
  <% end %>
  <br>
  <%= link_to_add_fields "Add Set", f, :numsets %><br><br>

  <%= f.fields_for :reps do |rep| %>
    <%= render "rep_fields", f: rep %>
  <% end %>

  <%= link_to_add_fields "Add Rep", f, :reps %><br><br>

</div>

app/views/workouts/_numset_fields.html.erb
<div id="numset_fields" class="row">
    <%= f.label "Sets", class: "col-lg-2 col-md-2 col-sm-2 col-xs-3" %>

    <%= f.text_field :number, class: "col-lg-4 col-md-5 col-sm-5 col-xs-6" %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "", "#", class: "remove_numset_fields col-lg-2 col-md-3 col-sm-5 col-xs-3 glyphicon glyphicon-remove" %>

</div>
<br>

app/views/workouts/_rep_fields.html.erb
<div id="rep_fields" class="row">
    <%= f.label "Reps", class: "col-lg-2 col-md-2 col-sm-2 col-xs-3" %>

    <%= f.text_field :number, class: "col-lg-4 col-md-5 col-sm-5 col-xs-6" %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "", "#", class: "remove_rep_fields col-lg-2 col-md-3 col-sm-5 col-xs-3 glyphicon glyphicon-remove" %>
</div>
<br>

app/views/workouts/_workoutForm.html.erb
<div class="workout-form col-lg-7 col-md-7 col-sm-8 col-xs-9">
  <%= form_for @workout do |f| %>
    <div class="form-group">
      <div class="row">

          <%= f.label :title, class: "col-lg-1 col-md-2 col-sm-2 col-xs-3" %>

          <%= f.text_field :title, class: "col-lg-4 col-md-4 col-sm-4 col-xs-6" %>

          <%= f.label "Category", class: "col-lg-2 col-md-2 col-sm-2 col-xs-4"  %>

        <div class="col-lg-4 col-md-3 col-sm-3 col-xs-3">
          <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :title, @workout.category_id) %>
        </div>
      </div>
        <br>
        <%= f.fields_for :exercises do |exercise| %>
          <%= render "exercise_fields", f: exercise %>
        <% end %>

          <%= link_to_add_fields "Add Exercise", f, :exercises %>
        <br><br>

    <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<%= render "workoutForm" %>

app/views/workouts/index.html.erb
<div class="bs-example col-md-7 col-md-offset-2 col-lg-7 col-lg-offset-2 col-sm-12 col-xs-12" data-example-id="hoverable-table">
  <h1>All Workouts</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <!-- <th>#</th> -->
        <th class="text-center"><h3>Workout</h3></th>
        <th class="text-center"><h3>Category</h3></th>
        <th class="text-center"><h3>Created By</h3></th>
      </tr>
    </thead>
    <tbody>
      <% @workouts.each do |workout| %>
      <tr>
        <!-- <th scope="row">1</th> -->
        <td class="text-center"><%= link_to "#{workout.title}", workout_path(workout) %></td>
        <td class="text-center"><%= link_to "#{workout.category.title}", category_path(workout.category) %></td>
        <td class="text-center"><%= link_to "#{workout.user.username}", user_path(workout.user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render "workoutForm" %>

app/views/workouts/show.html.erb
<h1>Workout Show Page</h1>
<div class="workout-show">
<h3>Workout Title: <%= @workout.title %></h3>
<h3>Created by: <%= link_to "#{@workout.user.username}", user_path(@workout.user) %></h3>
<h3>Category: <%= link_to @workout.category.title, category_path(@workout.category_id) %></h3>
<h3>Exercises:</h3>
  <% @workout.exercises.each do |exercise| %>
    <ul>
      <h4><li><%= exercise.name %></li></h4>
      <ul>
        <% exercise.numsets.each do |set| %>
        <li>Sets: <%= set.number %></li>
        <% end %>
        <% exercise.reps.each do |rep| %>
          <li>Reps: <%= rep.number %></li>
        <% end %>
      </ul>
    </ul>

  <% end %> <br>


  <%= link_to "Edit #{@workout.title}", edit_workout_path(@workout) %> &nbsp|&nbsp
  <%= link_to "Delete #{@workout.title}", workout_path(@workout), method: :delete %>
</div>